### ISSUE TITLE
DSL 4 issue: 'versioncmp' parameter 'a' expects a String value

### ISSUE THREAD

**Issue by andrewfraley** [voxpupuli/puppet-puppetboard#107]
I think this is a DSL 4 issue if virtualenv is not already installed:

Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /etc/puppetlabs/code/environments/production/modules/python/manifests/virtualenv.pp:121:11  at /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp:250

**Comment by igalic** [comment]
@andrewfraley shouldn't we attempt to fix that in @stankevich / puppet-python?

**Comment by wyardley** [comment]
Going to close this since it sounds like it's out of scope.
