### ISSUE TITLE
Adding ::puppetboard::apache::ldapauth?

### ISSUE THREAD

**Issue by mattock** [voxpupuli/puppet-puppetboard#110]
Hi,

Is there interest in having LDAP authentication setup baked in to puppetboard, e.g. in _::puppetboard::apache::ldapauth_. Basically one has to enable the _authnz_ldap_ module, which puppetlabs/apache can surely handle. Then an apache2 configuration fragment such as this needs to be put to _/etc/apache2/conf-enabled_ or equivalent:

```
<LocationMatch ^/puppetboard>
   AuthType Basic
   AuthName "Login to puppetboard with LDAP credentials"
   # These two are valid for Apache 2.2, but not really for 2.4
   Order Allow,Deny
   Allow from All

   AuthBasicProvider ldap
   AuthLDAPBindDN cn=proxy,dc=domain,dc=com
   AuthLDAPBindPassword secret_password
   AuthLDAPURL ldap://ldap.domain.com:389/ou=People,dc=domain,dc=com?cn
   AuthLDAPBindAuthoritative on

   Require valid-user
</LocationMatch>
```
Of course the above will eventually be need to extended to support different types of LDAP setups (e.g. anonymous binds), but I think it's a good starting point.

If you think this would be useful to having in this module I'm more than happy to implement it. Let me know what you think.

**Comment by bastelfreak** [comment]
Hi, this sounds great! I would be interested in having this, specially with anon bind.

**Comment by jyaworski** [comment]
I'm unsure if this needs to be in the puppetboard module. Could this be in a role or profile instead? I'm using mod_auth_pubtkt this way.

**Comment by mattock** [comment]
From how I understand the [roles and profiles pattern](http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/) the LDAP authentication could definitely be in a profile. However, profiles are inherently private, so everyone would be forced to reinvent the wheel.

That said, the code and template I suggested are actually _very_ general purpose and don't have any inherently puppetboard-specific code. So I think it should be made a define in an Apache module, which could then be used in a profile or directly from Hiera. I will probably implement the code as a define in [my apache module](https://github.com/Puppet-Finland/apache2).

**Comment by jyaworski** [comment]
@mattock I'm torn on this, because I can see both sides. While it would be nice to have a puppetboard tunable for this, that limits flexibility. For example, I use the puppetlabs-apache module. A lot of times modules do things like 'include apache' and I tune the options via hiera.

Is that something that would be amenable? <code>if puppetboard::apache::ldapauth { include apache::mod::ldap }</code>

**Comment by mattock** [comment]
@jyaworski I would keep the LDAP authentication parameters entirely separate from the main class to keep the main class interface manageable.  So you'd use the the ldapauth subclass like this:

    classes:
        - puppetboard
        - puppetboard::apache::ldapauth
    
    puppetboard::apache::ldapauth::bindn: 'cn=proxy, cd=domain, dc=com'
    puppetboard::apache::ldapauth::bindpw: 'password' 
    ...    

There would be no dependency to any particular apache puppet module, as long as we duplicate  basic Apache configurations (e.g. location of conf.d directory) in ::puppetboard::params. Which is probably a good idea, because in puppetlabs/apache they're broken.

**Comment by james-powis** [comment]
I personally have a need for such a thing as well... been scratching my head thinking about how to accomplish such a thing.

**Comment by mattock** [comment]
If my previous suggestion makes sense, I can implement it and issue a PR.

**Comment by rgevaert** [comment]
Actually, I'm in need to be able to enable CAS authentication.  The main point here is that the current vhost declaration is good but not very tunable.  You are forced not to use is if you need to change default behaviour.

**Comment by mattock** [comment]
I would prefer to add tunability (=new parameters) as needed. Right now the above virtualhost definition would solve my use-case.

Perhaps CAS authentication should be implemented as a separate subclass + template? Or would it end up being very similar to the above LDAP virtualhost?

**Comment by jamesmollison** [comment]
This should be resolved in #144

**Comment by dhoppe** [comment]
@jamesmollison Thx for the hint.

**Comment by mattock** [comment]
Good, somebody (else) bit the bullet :).
