### ISSUE TITLE
manage_* out of scope?

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-puppetboard#112]
Do manage_git and manage_virtualenv even make sense in this module? I would argue that they don't, and should be managed by some other module (for example, python or git).

**Comment by bastelfreak** [comment]
:+1: for removing it. That should be handled by seperate modules, all three combined in a profile.

**Comment by jyaworski** [comment]
Including ::python or ::git would be OK in itself, but nothing beyond that imo.

**Comment by nibalizer** [comment]
Fine by me
