### ISSUE TITLE
Release 2.7.5 to PuppetForge

### ISSUE THREAD

**Issue by apeeters** [voxpupuli/puppet-puppetboard#118]
Hi,

Please release 2.7.5 on PuppetForge. The version currently available (2.7.3) is broken because of https://github.com/voxpupuli/puppet-module-puppetboard/commit/80ef518595d6ed416a7e4f765210e9aadd5ea20a

Thanks!

**Comment by bastelfreak** [comment]
Hi. we just released a new version to the forge.
