### ISSUE TITLE
Add ability to override virtualenv package name

### ISSUE THREAD

**Issue by danieljamesscott** [voxpupuli/puppet-puppetboard#119]
I would like to be able to override the virtualenv package name. i.e. Add a new parameter to init.pp

`$virtualenv = $::puppetboard::params::virtualenv,`

**Comment by danieljamesscott** [comment]
Actually, I think that I really just need to be able to pass the version parameter to the python::virtualenv module:

https://github.com/voxpupuli/puppet-module-puppetboard/blob/master/manifests/init.pp#L252

**Comment by danieljamesscott** [comment]
Should I make a pull request for this?

**Comment by jyaworski** [comment]
@danieljamesscott absolutely. However, see https://github.com/voxpupuli/puppet-puppetboard/issues/112. It may be better to just remove that config entirely and do 'include ::python'.

**Comment by wyardley** [comment]
I think this is now not needed, please feel free to reopen if you disagree.
