### ISSUE TITLE
Add Ability to pass OFFLINE_MODE to settings.py

### ISSUE THREAD

**Issue by james-powis** [voxpupuli/puppet-puppetboard#130]
In environments where the user machine is unable to reach out to CDN's for remote assets, puppetboard has `OFFLINE_MODE = True` in settings.py to load those assets from disk. 

I will be adding the ability to manage this config setting in a future PR.

**Comment by james-powis** [comment]
Disregard, I did not know about extra_settings... For those who look at this:

``class { 'puppetboard':
  ...
  extra_settings => {
    OFFLINE_MODE => true
  }
  ...
}
``

**Comment by jyaworski** [comment]
@james-powis this is still a valid issue if you want it to be. I would accept a PR for such functionality.

**Comment by james-powis** [comment]
all right you twisted my arm... reopening

**Comment by james-powis** [comment]
PR #131 submitted
