### ISSUE TITLE
Puppet CA certificate not configured correctly

### ISSUE THREAD

**Issue by dvankeerppw** [voxpupuli/puppet-puppetboard#142]
Currently if you do not have the Puppet CA root certificate added to the root certificate authority file used by your operating system. You have to specific the puppet CA root certificate via the hack mentioned in the documentation, a.k.a:
```puppet
$ssl_dir = $::settings::ssldir
$puppetboard_certname = $::certname
class { 'puppetboard':
  ...
  puppetdb_ssl      => "${ssl_dir}/certs/ca.pem",
  ...
}
```
Puppetboard 2.8.2 does not allow the usage of puppetdb_ssl and currently even just uses the     puppetdb_ssl_verify => true/false toggle as the value to the generated settings.py of puppet board. 

```
cat settings.py 
PUPPETDB_SSL_VERIFY = true 
PUPPETDB_KEY = '/etc/puppetlabs/puppet/ssl/private_keys/puppetdb.sott.sleepscan.equilli.com.pem'
PUPPETDB_CERT = '/etc/puppetlabs/puppet/ssl/certs/puppetdb.sott.sleepscan.equilli.com.pem'
```

Once the value of PUPPETDB_SSL_VERIFY is changed to PUPPETDB_SSL_VERIFY='/etc/puppetlabs/puppet/ssl/certs/ca.pem' manually, the SSL verification works as expected. 

Is the provided documentation incorrect?  Or is this documentation for a future release?

**Comment by apeeters** [comment]
I created a pull request #150 which documents the correct usage (puppetdb_ssl_verify instead of puppetdb_ssl).

**Comment by wyardley** [comment]
#150 has been merged.
