### ISSUE TITLE
Option to control homedir for puppetboard user

### ISSUE THREAD

**Issue by akhomyakov** [voxpupuli/puppet-puppetboard#147]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 4.6.1
- Ruby: (doesn't seem to be installed)
- Distribution: Ubuntu 6.04.1 LTS (Xenial Xerus)
- Module version: 2.8.2
### How to reproduce (e.g Puppet code you use)

Classes:
        - 'puppetboard'
        - 'puppetboard::apache::vhost'
        - 'apache'
puppetboard::manage_virtualenv: 'true'
puppetboard::default_environment: '*'
puppetboard::apache::vhost::vhost_name: 'puppetboard000.example.com'
puppetboard::apache::vhost::port: '80'
### What are you seeing

Error: Could not create user puppetboard: Execution of '/usr/sbin/useradd -g puppetboard -s /bin/bash -m -r puppetboard' returned 12: useradd: cannot create directory /home/puppetboard
Error: /Stage[main]/Puppetboard/User[puppetboard]/ensure: change from absent to present failed: Could not create user puppetboard: Execution of '/usr/sbin/useradd -g puppetboard -s /bin/bash -m -r puppetboard' returned 12: useradd: cannot create directory /home/puppetboard
### What behaviour did you expect instead

My /home is actual an NFS target, so this is why it's failing. The module doesn't have a way to specify $homedir. I'd expect a way to control home dir for user puppetboard.

**Comment by homa2001** [comment]
Additionally, trying to get around the issue with 
puppetboard::user: 'puppet'
puppetboard::group: 'puppet'
puppetboard::manage_user: false
puppetboard::manage_group: false
Doesn't work either, because it seems like manage_user pretty much has to be true otherwise vcsrepo class that has require => user[$user] fails.

**Comment by homa2001** [comment]
One more comment: Basically, as a work around leaving the user at default (puppetboard), but editing the init.pp to make managehome => false let's the catalogue compile.

  if $manage_user {
    user { $user:
      ensure     => present,
      shell      => '/bin/bash',
      managehome => false,
      gid        => $group,
      system     => true,
      groups     => $groups,
      require    => Group[$group],
    }
 As far as I can see, there is no way to control this from class declaration.

**Comment by akhomyakov** [comment]
I have forgotten about this until now as I was rebuilding the puppet master. It appears that manage home is hard coded to true, but according to puppet docs https://docs.puppet.com/puppet/latest/types/user.html#user-attribute-home "The directory must be created separately and is not currently checked for existence." So I'm not sure exactly why this is, but I still have to create /home/puppetboard by hand.
If I want to manage the user externally to the module, I can't. E.g.:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Invalid relationship: File[/srv/puppetboard/puppetboard/wsgi.py] { require => User[puppetboard] }, because User[puppetboard] doesn't seem to be in the catalog
```
It seems to ignore $user and $group if $manage_user is set to false

```puppetboard::user: www-data
puppetboard::group: www-data
puppetboard::manage_user: false
puppetboard::manage_group: false```

**Comment by ffrank** [comment]
I think the "canonical" way to work around this is to

1. set `manage_user` to `false` and
2. add a custom `user` resource `before` the `puppetboard` class in order to create the user as appropriate for your environment.

Does that seem feasible to you?

I'm hesitant to expose too many details like that on the module interface, because this can lead to what I like to think of as "interface creep" (see also, the apache module).

**Comment by smortex** [comment]
034fde12b6497673b156f67c7133b24035d43b93 added a `$homedir` parameter. Closing.
