### ISSUE TITLE
Problem with installing puppetboard.

### ISSUE THREAD

**Issue by jimezdoesit** [voxpupuli/puppet-puppetboard#163]
I had to reinstall puppetdb & puppetboard. I have all of my stuff in gitlab. When I tried to reinstall puppetboard I got the below error. The only fix is to copy over /srv/puppetboard from another machine :-(

Notice: /Stage[main]/Puppetboard/Python::Virtualenv[/srv/puppetboard/virtenv-puppetboard]/Exec[python_virtualenv_/srv/puppetboard/virtenv-puppetboard]/returns: ValueError: I/O operation on closed file

Error: true && virtualenv --system-site-packages -p python /srv/puppetboard/virtenv-puppetboard && /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --help > /dev/null 2>&1 && { /srv/puppetboard/virtenv-puppetboard/bin/pip wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install $wheel_support_flag --upgrade pip setuptools || /srv/puppetboard/virtenv-puppetboard/bin/pip --log /srv/puppetboard/virtenv-puppetboard/pip.log install --upgrade pip setuptools ;} returned 1 instead of one of [0]
[pip.txt](https://github.com/voxpupuli/puppet-puppetboard/files/740997/pip.txt)

**Comment by mterzo** [comment]
Looking at the error log you posted over at https://github.com/voxpupuli/puppetboard/issues/343

This looks to be something with your python setup.  From the logs your error is here:

```
Using version 34.1.0 (newest of versions: 34.1.0, 34.0.3, 
...
Downloading/unpacking setuptools from https://pypi.python.org/packages/64/88/d434873ba1ce02c0ed669f574afeabaeaaeec207929a41b5c1ed947270fc/setuptools-34.1.0.zip#md5=a2f819c503b49781b1a15cfb4d49c974

  Downloading from URL https://pypi.python.org/packages/64/88/d434873ba1ce02c0ed669f574afeabaeaaeec207929a41b5c1ed947270fc/setuptools-34.1.0.zip#md5=a2f819c503b49781b1a15cfb4d49c974
  Running setup.py egg_info for package setuptools

    Traceback (most recent call last):
```

I haven't looked at this module, are you always getting "latest"?  

Also: https://pypi.python.org/pypi/setuptools/34.1.0  was released on the 29th.

**Comment by jimezdoesit** [comment]
yes as far as I know. I am running three modules that tie all of this in together. Abstractit/puppet, puppetlabs/puppetdb, puppet/puppetboard and all deps. I have never seen this error before. when I run a new setup of centos 7.2 or 7.3 and yum update. I will install puppetserver and all of the stuff. It has been fine before. I have not changes my process but rather something else has changed maybe? Not sure...

**Comment by jimezdoesit** [comment]
Not sure why this worked but I changed the fqdn hostname of the puppetdb host to local host. Before it was the fqdn hostname. I still get the error but puppetboard is working. closing the issue.

**Comment by mterzo** [comment]
The problem is you aren't updating, the problem isn't in puppetboard, it looks to be pip is failing to install setuptools.  Here's a really good chain:

https://github.com/pypa/setuptools/issues/937
