### ISSUE TITLE
Ability to define INVENTORY_FACTS parameter 

### ISSUE THREAD

**Issue by jordigg** [voxpupuli/puppet-puppetboard#164]
Would be nice to be able to define the `INVENTORY_FACTS` parameter in order to manage which facts are being used on the inventory tab.

**Comment by rkcpi** [comment]
You can manage `INVENTORY_FACTS` via the `extra_settings` parameter:

```
class { 'puppetboard':
  extra_settings    => {
    'INVENTORY_FACTS' => '[("Hostname","fqdn"),("IP Address","ipaddress")]'
  }
}
```
