### ISSUE TITLE
New install, puppetboard start error 

### ISSUE THREAD

**Issue by bissa** [voxpupuli/puppet-puppetboard#171]
Fresh install on 16.04 LTS
I installed a fresh puppetmaster a few days ago and it was working direct, and i don't see anything i have done differently this time.

## Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: server 2.7.2 agent 4.9.4
- Ruby: 2.3.1p112
- Distribution: Ubuntu 16.04 LTS
- Module version: 2.9.0

## How to reproduce (e.g Puppet code you use)
node puppet01 {

  class { 'puppetdb':
    manage_dbserver     => true,
    database            => 'postgres',
    postgres_version    => '9.5',
    manage_package_repo => false,
  }
  class { 'puppetdb::master::config':
    manage_report_processor => true,
    enable_reports => true,
  }
  class { 'puppetboard':
    manage_git        => 'latest',
    manage_virtualenv => 'latest',
  }
  class { 'apache': }
  class { 'apache::mod::wsgi': }
  class { 'puppetboard::apache::vhost':
    vhost_name => 'sth-puppetboard.internal.int',
    port       => 80,
  }
}

## What are you seeing
In /var/log/apache2/sth-puppetboard.internal.int_error.log
[Mon Mar 13 15:36:38.655244 2017] [wsgi:error] [pid 3964:tid 140468569270016] /srv/puppetboard/puppetboard/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
[Mon Mar 13 15:36:38.655276 2017] [wsgi:error] [pid 3964:tid 140468569270016]   from flask.ext.wtf import Form
[Mon Mar 13 15:36:38.774101 2017] [wsgi:error] [pid 3964:tid 140468569270016] /srv/puppetboard/puppetboard/puppetboard/forms.py:11: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Mon Mar 13 15:36:38.774137 2017] [wsgi:error] [pid 3964:tid 140468569270016]   class QueryForm(Form):
[Mon Mar 13 15:36:38.774227 2017] [wsgi:error] [pid 3964:tid 140468569270016] /srv/puppetboard/puppetboard/puppetboard/forms.py:33: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Mon Mar 13 15:36:38.774235 2017] [wsgi:error] [pid 3964:tid 140468569270016]   class CatalogForm(Form):
[Mon Mar 13 15:36:38.780769 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098] mod_wsgi (pid=3964): Target WSGI script '/srv/puppetboard/puppetboard/wsgi.py' cannot be loaded as Python module.
[Mon Mar 13 15:36:38.780793 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098] mod_wsgi (pid=3964): Exception occurred processing WSGI script '/srv/puppetboard/puppetboard/wsgi.py'.
[Mon Mar 13 15:36:38.780822 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098] Traceback (most recent call last):
[Mon Mar 13 15:36:38.780845 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098]   File "/srv/puppetboard/puppetboard/wsgi.py", line 15, in <module>
[Mon Mar 13 15:36:38.780905 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098]     from puppetboard.app import app as application
[Mon Mar 13 15:36:38.780918 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 130, in <module>
[Mon Mar 13 15:36:38.781233 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098]     abort.mapping[204] = NoContent
[Mon Mar 13 15:36:38.781259 2017] [wsgi:error] [pid 3964:tid 140468569270016] [remote 172.16.149.6:21098] AttributeError: 'function' object has no attribute 'mapping'

**Comment by furlongm** [comment]
Also seeing the same error on a fresh install:

```
/srv/puppetboard/puppetboard/puppetboard/forms.py:4: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
  from flask.ext.wtf import Form
Traceback (most recent call last):
  File "/srv/puppetboard/puppetboard/wsgi.py", line 15, in <module>
    from puppetboard.app import app as application
  File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 130, in <module>
    abort.mapping[204] = NoContent
AttributeError: 'function' object has no attribute 'mapping'
```

Installed using the puppetboard puppet module in a virtualenv.

**Comment by adenau** [comment]
+1 

on Mar 20 20:21:36.162670 2017] [:error] [pid 15648] [remote 10.0.1.154:144] mod_wsgi (pid=15648): Target WSGI script '/srv/puppetboard/puppetboard/wsgi.py' cannot be loaded as Python module.
[Mon Mar 20 20:21:36.162704 2017] [:error] [pid 15648] [remote 10.0.1.154:144] mod_wsgi (pid=15648): Exception occurred processing WSGI script '/srv/puppetboard/puppetboard/wsgi.py'.
[Mon Mar 20 20:21:36.162743 2017] [:error] [pid 15648] [remote 10.0.1.154:144] Traceback (most recent call last):
[Mon Mar 20 20:21:36.162774 2017] [:error] [pid 15648] [remote 10.0.1.154:144]   File "/srv/puppetboard/puppetboard/wsgi.py", line 15, in <module>
[Mon Mar 20 20:21:36.162881 2017] [:error] [pid 15648] [remote 10.0.1.154:144]     from puppetboard.app import app as application
[Mon Mar 20 20:21:36.162904 2017] [:error] [pid 15648] [remote 10.0.1.154:144]   File "/srv/puppetboard/puppetboard/puppetboard/app.py", line 130, in <module>
[Mon Mar 20 20:21:36.163333 2017] [:error] [pid 15648] [remote 10.0.1.154:144]     abort.mapping[204] = NoContent
[Mon Mar 20 20:21:36.163399 2017] [:error] [pid 15648] [remote 10.0.1.154:144] AttributeError: 'function' object has no attribute 'mapping'

**Comment by adenau** [comment]
Problem was fixed in PuppetBoard. 

https://github.com/voxpupuli/puppetboard/issues/370

I just updated to the latest version of PuppetBoard and everything is fine.

**Comment by bissa** [comment]
Yes works
