### ISSUE TITLE
NEEDHELP: spec tests doesn't run

### ISSUE THREAD

**Issue by toepi** [voxpupuli/puppet-puppetboard#199]
Not a real issue. More a question.

Have checkout latest master and run

```console
bundle install --path vendor/bundle
bundle exec rake spec
```

but some test failed (vhost doesn't contains concat anymore)

How should I contribute now - because can not verify my change do not break any other function.

**Comment by alexjfisher** [comment]
Interesting.  A PR was opened recently (a few hours ago) and the tests all pass there.  Could you paste the failure somewhere?  Or feel free to open a dummy PR of your own if you think you can get it to fail in travis.  Just mark it 'DO NOT MERGE' or something.  Thanks for getting involved.

**Comment by smortex** [comment]
Not experienced that, but I guess this was some tooling issue at some point… Ruby 2.3, Puppet 5/4… I think we can close this.
