### ISSUE TITLE
apache config dir wrong in Ubuntu

### ISSUE THREAD

**Issue by waipeng** [voxpupuli/puppet-puppetboard#204]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10
- Ruby: 2.1.5
- Distribution: Ubuntu 16.04
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)

Use the following example

```puppet
class { 'apache':
  purge_configs => false,
  mpm_module    => 'prefork',
  default_vhost => true,
  default_mods  => false,
}
class { 'apache::mod::wsgi': }
class { 'puppetboard': }
class { 'puppetboard::apache::conf': }
```

## What are you seeing

Error in running

Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /etc/apache2/conf.d/puppetboard.conf20180314-16269-1bzq3a.lock at /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/apache/conf.pp:88

## What behaviour did you expect instead

Use `/etc/apache2/conf-enabled` instead of `/etc/apache2/conf.d`

## Any additional information you'd like to impart

In Ubuntu 16.04, apache2 config dir is

```
root@puppet:~# dpkg -L apache2 | grep conf
/etc/apache2/conf-enabled
```

Seems that conf.d is in 12.04, and 14.04 onwards is conf-enabled

**Comment by bastelfreak** [comment]
Hi @waipeng, thanks for this bugreport. Are you able to provide a patch for this?
