### ISSUE TITLE
stankevich-python has been deprecated

### ISSUE THREAD

**Issue by mergwyn** [voxpupuli/puppet-puppetboard#215]
It's very recent, but the stankevich-python entry is puppet forge has this message:

```
This module has been deprecated by its author since June 27, 2018.
The reason given was:
This module has been adopted by Vox Populi.
The author has suggested puppet-python as its replacement.
```

I have made this replacement in my puppet file and the (limited) code I have still seems to work.

**Comment by bastelfreak** [comment]
Hi @mergwyn, thanks for reporting this issue. Are you able to provide a patch the updates the namespace for the python module in the metadata.json?
