### ISSUE TITLE
New version of CommonMark has changed the name to lower case -> commonmark

### ISSUE THREAD

**Issue by danieljamesscott** [voxpupuli/puppet-puppetboard#223]
A new release of CommonMark (0.8.0 and higher) is causing an issue because they have changed the name from CommonMark -> commonmark.

https://github.com/rtfd/CommonMark-py/blob/master/CHANGELOG.md#080-2018-09-03

Two possible solutions:
1. Hardcode the dependency to the prior version (0.7.5)
2. Change the dependency references to lower case.

**Comment by kenyon** [comment]
Fixed in https://github.com/voxpupuli/puppetboard/pull/497
