### ISSUE TITLE
Duplicate statement of the 'virtualenv' package with the python module

### ISSUE THREAD

**Issue by aeciopires** [voxpupuli/puppet-puppetboard#225]
The manifest "python/manifests/install.pp" in line 54 and manifest "puppetboard/manifests/init.pp" in line 269 have duplicate declaration resource for package virtualenv. Tested in CentOS7

`Error: Failed to apply catalog: Cannot alias Package[virtualenv] to ["python-virtualenv", :yum] at (file: /etc/puppetlabs/code/environments/production/modules/python/manifests/install.pp, line: 54); resource ["Package", "python-virtualenv", :yum] already declared (file: /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp, line: 269)
`

**Comment by bastelfreak** [comment]
Hi @aeciopires. I think those resources should be wrapped in https://github.com/puppetlabs/puppetlabs-stdlib#ensure_packages. Could you provide a PR for this?

**Comment by aeciopires** [comment]
Hi @bastelfreak, the problem occurred in Debian 9, Ubuntu Server 18.04 and CentOS 7.

I tested the current code of module and worked in Debian 9, Ubuntu Server 18.04 and CentOS 7.

The solution is generate new version of module puppet-puppetboard at Puppet-Forge. :-)

**Comment by smortex** [comment]
v5.0.0 was released a few weeks later, closing.
