### ISSUE TITLE
Listen IP of Apache Vhost is not configurable

### ISSUE THREAD

**Issue by ctriegg** [voxpupuli/puppet-puppetboard#226]
## Affected Puppet, Ruby, OS and module versions/distributions

All versions

## How to reproduce (e.g Puppet code you use)

Try to configure a listen IP for Apache

## What are you seeing

No configuration parameter for Apache listen IP. 

## What behaviour did you expect instead

A parameter for configuring the listen IP 

## Output log

-

## Any additional information you'd like to impart

-

**Comment by ctriegg** [comment]
I've missed that there is the "new" parameter `custom_apache_parameters` which missed in the older version we've been using. Sorry for the disturbance. :)

**Comment by SiteDesignUSA** [comment]
Hello. I know this is 8 months old but I cannot find anything on how to use this "custom_apache_parameters". Can anyone point me to documentation?
