### ISSUE TITLE
params class leaks wrong selinux context

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-puppetboard#228]
params.pp sets the following SELinux context for all File resources on Redhat:

```puppet
File {
  seltype => 'httpd_sys_content_t',
}
```

This attribute 'leaks' even to files that shouldn't have this context set, for example,
`/etc/httpd/conf.d/puppetboard.conf`, which should have `httpd_config_t`.

In addition, I think module's attribute `manage_selinux` should also cover `seltype`, not just `selbooleans`

**Comment by bastelfreak** [comment]
Hi @vchepkov, thanks for bringing this up. Are you able to provide a fix for this bug?

**Comment by d1nuc0m** [comment]
@bastelfreak @vchepkov is this issue still valid? I can't even find params.pp :sweat_smile:

**Comment by kenyon** [comment]
`params.pp` was removed in commit 5b643d9e133ad544ba0e976b099b112571e0b8ae so I'll close this.
