### ISSUE TITLE
catalog failure is not reflected in node status

### ISSUE THREAD

**Issue by rj667** [voxpupuli/puppet-puppetboard#235]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.8
- Ruby: 2.4.4p296
- Distribution: Debian stretch
- Module version: 5.0.0

## How to reproduce (e.g Puppet code you use)
Any invalid puppet code so the catalog fails to compile.

## What are you seeing
The system log on the node shows:
Nov 12 13:41:33 someserver.xs4all.net puppet-agent[27804]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'enabled' (file: /data/puppet/environments/production/modules/dnsdist/manifests/init.pp, line: 48) on Service[dnsdist-exporter] (file: /data/puppet/environments/production/modules/dnsdist/manifests/init.pp, line: 48) on node someserver.xs4all.net
Nov 12 13:41:50 someserver.xs4all.net puppet-agent[27804]: Applied catalog in 15.08 seconds

In Puppetboard this was displayed as status "unchanged"

## What behaviour did you expect instead

I expected Puppetboard to display this as status "failed".

## Output log

Opening the report in Puppetboard shows all resources as "skipped" and under Log I see:
Timestamp	Source	Tags	Message	Location
Nov 12 2018 - 13:41:33	Puppet	err	Could not retrieve catalog [etc. same as above]
Nov 12 2018 - 13:41:50	Puppet	notice	Applied catalog in 15.08 seconds

**Comment by initrd** [comment]
Agree with the OP. It would be nice to get any visibility into this issue. Moving from Foreman, this is a big gap in visibility of hosts that are either failing catalog compilation, or failing to apply resources.

**Comment by gdubicki** [comment]
I think that this actually Puppetboard's issue, not this project's, and that it is already reported there as https://github.com/voxpupuli/puppetboard/issues/449 .

I propose to close this issue here then.
