### ISSUE TITLE
Use the $custom apache parameters to set up puppetboard with basic auth

### ISSUE THREAD

**Issue by SiteDesignUSA** [voxpupuli/puppet-puppetboard#243]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)
Cannot find details on how to use the $custom apache parameters in the README.md for setting up and installing Puppetboard on the puppetmaster.
## What are you seeing
No help anywhere for how to add parameters to the apache httpd.conf file for each VirtualHost. I'd like to see an example of how to, for example, add basic auth to puppetboard using $custom apache parameters . Google shows only 4-6 results depending on search terms and most of those are links to commit https://github.com/voxpupuli/puppet-puppetboard/commit/7d79545bde3d41fb779a2bfcdb9956318c6de95e and another issue #226 (https://github.com/voxpupuli/puppet-puppetboard/issues/226) where nothing was explained.
## What behaviour did you expect instead
I'm trying to add the ability for basic auth in the VirtualHost block the puppet way for Puppetboard, but I can't seem to figure out how to go about it. When I try the code below, the <Directories> block just disappears. I'd like to amend the Puppetboard VirtualHost <directory> and <location> blocks.

I think an example or two on the README.md page showing how to add custom parameters to the apache virtualhost block would be nice. Directory, Location are two that come to mind.

Thanks for considering. I'm just a Wordpress hacker with a few servers and thought I'd try Puppet. I'd really like to use Puppetboard and I think an example would help, not only me, but many others who just aren't as stubborn as I am. Puppetboard seems to be the only GUI for puppetdb standing at this point and this might help with adoption and solidify a strong, loyal following.
## Output log
None.
## Any additional information you'd like to impart
I picked this up from bits and pieces and I don't really understand how this works (It's not...)

```puppet
  class { 'puppetboard::apache::vhost':
    vhost_name              =>  'fake.web.site',
    port                    =>  1797,
    custom_apache_parameters => {
  directories => {
  provider => 'Directory',
  custom_fragment => ['
          AuthType Basic
          AuthName "Restricted Files"
          AuthBasicProvider file
          AuthUserFile "/home/puppetboard/.htpasswd/.pass"
          Require user puppetboard
          Options Indexes FollowSymLinks MultiViews
          AllowOverride None'
    ],
  }

}
  }
```

**Comment by vchepkov** [comment]
I think more advanced features are out of scope of this module. Here is a fragment of my profile

```
  if $auth_file {
    apache::custom_config { 'puppetboard base authentication':
      filename => 'puppetboard-auth.conf',
      content  => epp("${module_name}/puppetboard-auth.conf.epp", {
        auth_file => $auth_file,
        location  => $puppetboard::apache::conf::wsgi_alias,
      }),
    }
  }
```
puppetboard-auth.conf.epp:
```
<%- |
  Stdlib::Unixpath $auth_file,
  Stdlib::Unixpath $location,
| -%>
<LocationMatch ^<%= $location %>>
   AuthType Basic
   AuthName "Login to puppetboard"
   <IfVersion < 2.4>
     Order Deny,Allow
     Allow from all
   </IfVersion>
    <IfVersion >= 2.4>
      Require all granted
    </IfVersion>

   AuthBasicProvider file
   AuthUserFile <%= $auth_file %>
   Require valid-user
</LocationMatch>
```

**Comment by b4ldr** [comment]
@SiteDesignUSA I have not used this feature from the apache module but looking at the [documentation](https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/vhost.pp#L1308-L1372) i think you have a few syntax error.  Try the following

```puppet
$basic_auth_frag = @(CONFIG)
AuthType Basic
AuthName "Restricted Files"
AuthBasicProvider file
AuthUserFile "/home/puppetboard/.htpasswd/.pass"
Require user puppetboard
Options Indexes FollowSymLinks MultiViews
AllowOverride None
| CONFIG
class { 'puppetboard::apache::vhost':
  vhost_name =>  'fake.web.site',
  port =>  1797,
  custom_apache_parameters => {
    directories => [{
      provider => 'location',
      path => '/'
      custom_fragment => $basic_auth_frag
    },],
  },
}

**Comment by SiteDesignUSA** [comment]
@vchepkov & @b4ldr Thanks for the help. I know its been awhile but I needed this functionality again after living without it and I chose @b4ldr 's code (just because it was simpler.) 

FYI, I looked over the missing comma at `path => '/'` in the code but got it sorted.
