### ISSUE TITLE
Support vcsrepo v3.0.0

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/puppet-puppetboard#245]
Allow puppetlabs/vcsrepo v3.0.0

https://github.com/puppetlabs/puppetlabs-vcsrepo/blob/master/CHANGELOG.md

**Comment by pjonesIDBS** [comment]
This has been actioned in #251 along with fixes for some other dependencies in related repos. A new release with the updates should be forthcoming soon.

**Comment by pjonesIDBS** [comment]
This can be closed now as it's fixed in version 6.0.0 available in the forge now.
