### ISSUE TITLE
manage_git and manage_virtualenv cannot be set to latest as readme suggests

### ISSUE THREAD

**Issue by trenta** [voxpupuli/puppet-puppetboard#253]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.9
- Ruby:
- Distribution: Ubuntu 18.04
- Module version:

## How to reproduce (e.g Puppet code you use)

```puppet
manage_git        => 'latest',
manage_virtualenv => 'latest',
```

## What are you seeing
Fails

`manage_virtualenv` and `manage_git` expect a Bool value and not a string

**Comment by cvquesty** [comment]
Seeing this as well.

**Comment by shoddyguard** [comment]
Also seeing this:
```
parameter 'manage_git' expects a Boolean value, got String
 parameter 'manage_virtualenv' expects a Boolean value, got String
```
