### ISSUE TITLE
Drop RedHat/CentOS 6/7 support due to missing Python 3.6 support in apache

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-puppetboard#294]
Puppetboard requires Python 3.6 or newer to run properly. This module also supports setting up apache with wsgi to talk to Puppetboard. CentOS 6 and 7 do not support it. CentOS 7 has Python 3.6, but no wsgi module is available for this version. This change will be done in https://github.com/voxpupuli/puppet-puppetboard/pull/292

**Comment by h0tw1r3** [comment]
We use gunicorn with apache + python36 and CentOS 7. There are zero issues.
CentOS 7 is supported until 2024? I'm confused by this merge and it's reasoning.

**Comment by kenyon** [comment]
> We use gunicorn with apache + python36 and CentOS 7. There are zero issues.
> CentOS 7 is supported until 2024? I'm confused by the reasoning for dropping support so soon. RHEL/Centos 7 are widely used in the enterprise.

Per the first comment, "CentOS 7 has Python 3.6, but no wsgi module is available for this version". It looks like you can get this via the https://ius.io repos though: https://github.com/iusrepo/python36-mod_wsgi
So I suppose in theory this could be supported.

**Comment by bastelfreak** [comment]
@h0tw1r3 this module sets up apache with wsgi. this didnt work properly with centos 7 and we had to do a release to publish fixes for the other operating systems. I am happy to review PRs for CentOS 7 if they pass the acceptance tests. But given my limited time I probably wont implement this myself.
