### ISSUE TITLE
Does this module upgrade Puppetboard?

### ISSUE THREAD

**Issue by mike406** [voxpupuli/puppet-puppetboard#303]
I am looking to see if this module supports upgrading Puppetboard installations, and if so how? In my case, I am looking to upgrade from 2.1.2 to 2.2.0.

Thanks

**Comment by vchepkov** [comment]
I think only if you are using git as the source

**Comment by mike406** [comment]
Poked around in the code. I don't think it does auto-upgrade based off the vcsrepo resource using ensure => present rather than ensure => latest

Line 232 in puppetboard/manifests/init.pp
'''
  vcsrepo { "${basedir}/puppetboard":
    **ensure   => present,**
    provider => git,
    owner    => $user,
    source   => $git_source,
    revision => $revision,
    require  => [
      User[$user],
      Group[$group],
    ],
  }
'''

**Comment by vchepkov** [comment]
revision is there

**Comment by mike406** [comment]
There is no way to change $revision without modifying the module code itself. It is hardcoded to undef rather than using a parameter. Also my understanding with the way vcsrepo resource works is that once Puppetboard is installed, it satisfies the "present" criteria so changing revision after the fact will not prompt Puppet to install over top again.

**Comment by vchepkov** [comment]
You can override default class parameter either with hiera or explicit class call
It worked for me fine

```
By default, vcsrepo will use the HEAD of the source repository's master branch. To use another branch or a specific commit, set revision to either a branch name or a commit SHA or tag.
```

**Comment by mike406** [comment]
I see, apologies for misunderstanding the override mechanics. I set revision to an explicit commit and that did work. Appreciate the clarifications and assistance.
