### ISSUE TITLE
Use python3-pip instead of python-pip

### ISSUE THREAD

**Issue by s1e2b3i4** [voxpupuli/puppet-puppetboard#311]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.18.0
- Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu
- Distribution: Ubuntu 20.04
- Module version: 7.0.1

## How to reproduce (e.g Puppet code you use)

Normal installation of the module.

## What are you seeing

It tries to install `python-pip`. However, this is not available in the package sources.

## What behaviour did you expect instead

It should install `python3-pip` instead.

## Output log

```sh
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-pip' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-pip
```

**Comment by andersje** [comment]
i too am encountering this.  Did you ever find a workaround?

**Comment by s1e2b3i4** [comment]
> i too am encountering this. Did you ever find a workaround?

Unfortunately, no.  I ended up installing everything manually.

**Comment by andersje** [comment]
Yep, me too.   Gave up on using the puppet module until such a time as a fix goes in.

**Comment by sebastianberm** [comment]
This issue is that https://github.com/voxpupuli/puppet-python/pull/576 (and probably new related stuff) has to be resolved, before this can be done.

**Comment by dowlingw** [comment]
It looks like https://github.com/voxpupuli/puppet-python/pull/593 has been merged to address this, so this is doable now.

I have also observed this issue with Debian 11, though I will probably raise a separate issue against this project to track that specifically. Support for that has also been merged with https://github.com/voxpupuli/puppet-python/pull/621

**Comment by kenyon** [comment]
This should be resolved now.
