### ISSUE TITLE
Could not find resource

### ISSUE THREAD

**Issue by summerm78** [voxpupuli/puppet-puppetboard#322]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.21.0-1.el8.x86_64
- Ruby:
- Distribution: RHEL 8.3
- Module version: v7.0.2
- Python 3.6.8

## What are you seeing

After upgrading from rhel 7 to rhel 8 puppet fails with
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Python::Virtualenv[/opt/puppetboard/virtenv-puppetboard]' in parameter 'require' (file: /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp, line: 174) on node server.example.com`

Is there a way to get more information about what is failing?

**Comment by tuxmea** [comment]
Issue is due to an update of https://github.com/voxpupuli/puppet-python .
The update to v5 of python module removed the python::virtualenv defined type.

Solution: downgrade python module to v4.1.1

**Comment by tuxmea** [comment]
@summerm78 please let us know of downgrading python solves this issue.

**Comment by summerm78** [comment]
Downgraded the python module to v4.1.1 - now I get another error.
`Error: Facter: error while resolving custom fact "virtualenv_version": undefined method `[]' for nil:NilClass
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Python::Virtualenv[/opt/puppetboard/virtenv-puppetboard]' in parameter 'require' (file: /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp, line: 174) on node adzh-srlp-pdb01.intern.cube.ch
`
But I think this has to do with the python module. I'll take a look at that.

**Comment by summerm78** [comment]
After changing /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp `      require => [
        File["${basedir}/puppetboard"],
        Python::Virtualenv["${basedir}/virtenv-puppetboard"]
      ],`
to `      require => [
        File["${basedir}/puppetboard"],
#        Python::Virtualenv["${basedir}/virtenv-puppetboard"]
      ],`
we were able to install puppetboard. Our site.pp is now 
`  }
  class { 'python':
    use_epel => false,
    version    => '3',
    pip        => 'present',
    virtualenv => 'present',
  }
  class { 'puppetboard':
    offline_mode => true,
    basedir  => '/opt/puppetboard',
    listen  => 'public',
    python_proxy  => 'http://our_proxy:8080',
    reports_count     => 40, 
    manage_git        => true,
    manage_virtualenv => false,
    manage_selinux => false,
    default_environment => '*',
    python_version => '3.6',
  }`
