### ISSUE TITLE
Puppet-python version dependency update

### ISSUE THREAD

**Issue by Sarcasm0naut** [voxpupuli/puppet-puppetboard#326]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Ruby:
- Distribution: 
- Module version: 7.0.2

## How to reproduce (e.g Puppet code you use)
When pinning the puppet-python module version to the latest, 6.0.0, a dependency failure occurs as this module requires puppet-python to be < 6.0.0

## What behaviour did you expect instead
I'd be highly appreciated if this dependency could be bumped to at least <= 6.0.0

**Comment by rledousa** [comment]
+1
