### ISSUE TITLE
Python version 3.8 incorrect for Debian 11

### ISSUE THREAD

**Issue by JohanThelander** [voxpupuli/puppet-puppetboard#350]
It appears that the Puppetboard module lists Python 3.8 for Debian 11 as per the file included in the module:
puppetboard/data/os/Debian.11.yaml

This file includes:
puppetboard::python_version: '3.8'

The final Python version that shipped with Debian 11 is in fact, Python 3.9, making the default specified in this file incorrect as it should include:
puppetboard::python_version: '3.9'

Any chance this can be resolved?

**Comment by smortex** [comment]
Was fixed in 9bf0b7be49b6e0261906f12624b21a84a17ae89f.
