### ISSUE TITLE
Please release 9.0.0

### ISSUE THREAD

**Issue by gdubicki** [voxpupuli/puppet-puppetboard#362]
Hi! 

I got a report about an issue with installing Puppetboard 4.0.1 (https://github.com/voxpupuli/puppetboard/issues/704) and I am not having such problem when using this module but from a commit.

If the fix turns out to be using this module in the latest, unreleased version, then it would be good to make a release.

I can prepare a new release PR like https://github.com/voxpupuli/puppet-puppetboard/pull/356 if that would help, please let me know.

ping @smortex @bastelfreak

**Comment by smortex** [comment]
Hey, no objection from me for a new release :-)

Please create a branch, bump the version, update the changelog (`bundile exec rake changelog`) and you should be ready to fill-in a PR :wink: Thanks!

**Comment by gdubicki** [comment]
In the end this has been done by @zaben903 (thanks!) in #363 and v9.0.0 has been released. :)
