### ISSUE TITLE
Please release 9.1.0

### ISSUE THREAD

**Issue by Chartreusito** [voxpupuli/puppet-puppetboard#383]
I'm trying to install puppetboard running within venv on Debian 11 with Puppet7 or Puppet8, and i'm stuck fixing manually the init.pp file as it does not handle python venv requirements when parameter manage_virtualenv is true.

I see that's it's been fixed since last august by @h0tw1r3 in the following commit but that no release was made since then.

https://github.com/voxpupuli/puppet-puppetboard/commit/7b8032786cf5deb140a059c70e67728655618117

Could anyone qualified please release a new patch to include this already commited fix ?

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7 or 8
- Ruby:
- Distribution: Debian 11
- Module version: 9.0.0

**Comment by gdubicki** [comment]
Because of https://github.com/voxpupuli/puppet-puppetboard/pull/375, which is backward-incompatible as it requires an extra parameter, we should release v. 10.0.0 now.

**Comment by h0tw1r3** [comment]
[v10.0.0](https://github.com/voxpupuli/puppet-puppetboard/releases/tag/v10.0.0) released a while ago. Enjoy!
