### ISSUE TITLE
No unit tests?

### ISSUE THREAD

**Issue by ffrank** [voxpupuli/puppet-puppetboard#90]
I notice that we have acceptance tests for PCCI but no `rspec-puppet` based unit tests. Was this a concious decision?

**Comment by jyaworski** [comment]
@ffrank very likely it was not a conscious decision. It just happens.

Tests are welcome, but our policy is to not _enforce_ tests. We do encourage them, though.

**Comment by wyardley** [comment]
There are now class specs, I think this can be closed.
